//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSave
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int MemoryPowerRound { get; set; }
        public int MemoryPowerPoints { get; set; }
        public int LeftOrRightRound { get; set; }
        public int LeftOrRightPoints { get; set; }
        public int MultiTaskingRound { get; set; }
        public int MultiTaskingPoints { get; set; }
        public int RememberFacesRound { get; set; }
        public int RememberFacesPoints { get; set; }
    }
}
